// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_opengl3.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "dcimgui_impl_opengl3.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::imgui_impl_opengl3_init(void)
{
    return ::ImGui_ImplOpenGL3_Init();
}

CIMGUI_IMPL_API bool cimgui::imgui_impl_opengl3_init_ex(const char* glsl_version)
{
    return ::ImGui_ImplOpenGL3_Init(glsl_version);
}

CIMGUI_IMPL_API void cimgui::imgui_impl_opengl3_shutdown(void)
{
    ::ImGui_ImplOpenGL3_Shutdown();
}

CIMGUI_IMPL_API void cimgui::imgui_impl_opengl3_new_frame(void)
{
    ::ImGui_ImplOpenGL3_NewFrame();
}

CIMGUI_IMPL_API void cimgui::imgui_impl_opengl3_render_draw_data(cimgui::ImDrawData* draw_data)
{
    ::ImGui_ImplOpenGL3_RenderDrawData(reinterpret_cast<::ImDrawData*>(draw_data));
}

CIMGUI_IMPL_API bool cimgui::imgui_impl_opengl3_create_fonts_texture(void)
{
    return ::ImGui_ImplOpenGL3_CreateFontsTexture();
}

CIMGUI_IMPL_API void cimgui::imgui_impl_opengl3_destroy_fonts_texture(void)
{
    ::ImGui_ImplOpenGL3_DestroyFontsTexture();
}

CIMGUI_IMPL_API bool cimgui::imgui_impl_opengl3_create_device_objects(void)
{
    return ::ImGui_ImplOpenGL3_CreateDeviceObjects();
}

CIMGUI_IMPL_API void cimgui::imgui_impl_opengl3_destroy_device_objects(void)
{
    ::ImGui_ImplOpenGL3_DestroyDeviceObjects();
}

#endif // #ifndef IMGUI_DISABLE
