name: Build

on:
  push:
  pull_request:

env:
  CMAKE_PRESET: release

jobs:
  build:
    # For reference when cross-platform support is added:
    # https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure CMake
        run: cmake --preset ${{env.CMAKE_PRESET}}

      - name: Build
        run: cmake --build -j $(nproc) --preset ${{env.CMAKE_PRESET}}

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/${{env.CMAKE_PRESET}}/memsed
